"""
Report Exporter

This module provides helper functions for saving processed synthetic CGM
data and summary reports.

Important:
This project uses synthetic data only. Reports generated by this module are
for educational and portfolio purposes only.
"""

from pathlib import Path

import pandas as pd


def save_dataframe_to_csv(
    df: pd.DataFrame,
    output_path: str | Path,
) -> Path:
    """
    Save a DataFrame to a CSV file.

    Args:
        df: DataFrame to save.
        output_path: Destination CSV path.

    Returns:
        Path to the saved CSV file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    df.to_csv(output_path, index=False)

    return output_path


def save_multiple_reports(
    reports: dict[str, pd.DataFrame],
    output_dir: str | Path,
) -> dict[str, Path]:
    """
    Save multiple report DataFrames to CSV files.

    Args:
        reports: Dictionary mapping report names to DataFrames.
        output_dir: Directory where reports should be saved.

    Returns:
        Dictionary mapping report names to saved file paths.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    saved_paths = {}

    for report_name, report_df in reports.items():
        output_path = output_dir / f"{report_name}.csv"
        report_df.to_csv(output_path, index=False)
        saved_paths[report_name] = output_path

    return saved_paths
